#include "PluginProcessor.h"
#include "PluginEditor.h"
PhasePocketAudioProcessor::PhasePocketAudioProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withInput("Sidechain",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),parameters(*this,nullptr,"PARAMETERS",layout()){
 influence=parameters.getRawParameterValue("amount");smoothing=parameters.getRawParameterValue("release");mode=parameters.getRawParameterValue("mode");scLow=parameters.getRawParameterValue("scLow");scHigh=parameters.getRawParameterValue("scHigh");bypass=parameters.getRawParameterValue("bypass");msBalance=parameters.getRawParameterValue("msBalance");duration=parameters.getRawParameterValue("duration");sustain=parameters.getRawParameterValue("sustain");requestedMode.store(mode->load()>.5f?1:0);activeMode.store(requestedMode.load());setLatencySamples(pocket::Engine::latency(activeMode.load()));parameters.addParameterListener("mode",this);
}
PhasePocketAudioProcessor::~PhasePocketAudioProcessor(){parameters.removeParameterListener("mode",this);cancelPendingUpdate();}
juce::AudioProcessorValueTreeState::ParameterLayout PhasePocketAudioProcessor::layout(){std::vector<std::unique_ptr<juce::RangedAudioParameter>> p;
 p.push_back(std::make_unique<juce::AudioParameterFloat>("amount","Influence",juce::NormalisableRange<float>(0,150,.1f),100));p.push_back(std::make_unique<juce::AudioParameterFloat>("tolerance","Legacy Tolerance",0.f,6.f,1.f));p.push_back(std::make_unique<juce::AudioParameterFloat>("low","Legacy Low",20.f,150.f,25.f));p.push_back(std::make_unique<juce::AudioParameterFloat>("high","Legacy High",80.f,500.f,220.f));p.push_back(std::make_unique<juce::AudioParameterFloat>("maxReduction","Legacy Reduction",0.f,48.f,24.f));p.push_back(std::make_unique<juce::AudioParameterFloat>("release","Smoothing",juce::NormalisableRange<float>(0,500,.1f,.4f),40));p.push_back(std::make_unique<juce::AudioParameterBool>("phaseAware","Legacy Phase",true));p.push_back(std::make_unique<juce::AudioParameterChoice>("mode","Mode",juce::StringArray{"Spectrum","Amplitude"},1));p.push_back(std::make_unique<juce::AudioParameterFloat>("scLow","Sidechain Low",juce::NormalisableRange<float>(20,20000,1,.2f),20));p.push_back(std::make_unique<juce::AudioParameterFloat>("scHigh","Sidechain High",juce::NormalisableRange<float>(20,20000,1,.2f),20000));p.push_back(std::make_unique<juce::AudioParameterBool>("bypass","Bypass",false));p.push_back(std::make_unique<juce::AudioParameterFloat>("msBalance","Mid Side balance",juce::NormalisableRange<float>(-1,1,.001f),0));p.push_back(std::make_unique<juce::AudioParameterFloat>("duration","Sidechain Duration",juce::NormalisableRange<float>(1,2000,1,.35f),2000));p.push_back(std::make_unique<juce::AudioParameterFloat>("sustain","Sidechain Sustain",juce::NormalisableRange<float>(0,100,.1f),100));return {p.begin(),p.end()};}
void PhasePocketAudioProcessor::parameterChanged(const juce::String& id,float value){if(id!="mode")return;requestedMode.store(value>.5f?1:0,std::memory_order_release);triggerAsyncUpdate();}
void PhasePocketAudioProcessor::handleAsyncUpdate(){applyRequestedMode();}
void PhasePocketAudioProcessor::applyRequestedMode(){const int chosen=requestedMode.load(std::memory_order_acquire),latency=pocket::Engine::latency(chosen);if(getLatencySamples()!=latency)setLatencySamples(latency);activeMode.store(chosen,std::memory_order_release);}
void PhasePocketAudioProcessor::prepareToPlay(double sr,int){const int chosen=mode->load()>.5f?1:0;requestedMode.store(chosen);activeMode.store(chosen);setLatencySamples(pocket::Engine::latency(chosen));engine.reset(sr,influence->load()*.01f,chosen);decimation=juce::jmax(1,(int)(sr/1200));captured=0;capture={};}
void PhasePocketAudioProcessor::reset(){engine.reset(juce::jmax(1.,getSampleRate()),influence->load()*.01f,activeMode.load());captured=0;capture={};}
bool PhasePocketAudioProcessor::isBusesLayoutSupported(const BusesLayout& l) const{if(l.inputBuses.size()!=2||l.outputBuses.size()!=1)return false;auto in=l.getMainInputChannelSet(),out=l.getMainOutputChannelSet(),side=l.getChannelSet(true,1);return in==out&&(out==juce::AudioChannelSet::mono()||out==juce::AudioChannelSet::stereo())&&(side.isDisabled()||side==juce::AudioChannelSet::mono()||side==juce::AudioChannelSet::stereo());}
void PhasePocketAudioProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer& m){processAudio(b,m,false);}
void PhasePocketAudioProcessor::processAudio(juce::AudioBuffer<float>& buffer,juce::MidiBuffer&,bool hostBypass){juce::ScopedNoDenormals noDenormals;auto main=getBusBuffer(buffer,true,0),side=getBusBuffer(buffer,true,1);bool bypassed=hostBypass||bypass->load()>.5f;displayBypass.store(hostBypass,std::memory_order_relaxed);engine.configure(influence->load()*.01f,smoothing->load(),activeMode.load(std::memory_order_acquire),scLow->load(),scHigh->load(),bypassed,msBalance->load(),duration->load(),sustain->load()*.01f);unsigned frameBefore=engine.getFrameCounter();if(main.getNumChannels()==0)return;
 float peak=0,minimum=1;double traceStep=1./juce::jmax(1.,getSampleRate());bool showTrace=editorOpen.load(std::memory_order_relaxed);for(int n=0;n<buffer.getNumSamples();++n){std::array<float,2>b{},k{};for(int c=0;c<2;++c){b[c]=main.getSample(juce::jmin(c,main.getNumChannels()-1),n);if(side.getNumChannels()>0)k[c]=side.getSample(juce::jmin(c,side.getNumChannels()-1),n);}peak=juce::jmax(peak,std::abs(k[0]),std::abs(k[1]));auto v=engine.process(b,k);for(int c=0;c<main.getNumChannels();++c)main.setSample(c,n,v.out[(size_t)c]);minimum=juce::jmin(minimum,v.gain);traceTime+=traceStep;if(!showTrace){captured=0;continue;}capture.time=traceTime;if(captured==0)capture={v.dry[0],v.dry[0],v.key[0],v.key[0],v.out[0],v.out[0],v.gain,traceTime};else{capture.inLo=juce::jmin(capture.inLo,v.dry[0]);capture.inHi=juce::jmax(capture.inHi,v.dry[0]);capture.keyLo=juce::jmin(capture.keyLo,v.key[0]);capture.keyHi=juce::jmax(capture.keyHi,v.key[0]);capture.outLo=juce::jmin(capture.outLo,v.out[0]);capture.outHi=juce::jmax(capture.outHi,v.out[0]);capture.gain=juce::jmin(capture.gain,v.gain);}if(++captured>=decimation){int a,s,b2,s2;fifo.prepareToWrite(1,a,s,b2,s2);if(s){traces[(size_t)a]=capture;fifo.finishedWrite(1);}captured=0;}}
 keyPeak.store(peak);gainMeter.store(minimum);if(showTrace&&frameBefore!=engine.getFrameCounter()){int a,s,b,c;spectrumFifo.prepareToWrite(1,a,s,b,c);if(s){engine.readCurve(spectrumTraces[(size_t)a].mid,spectrumTraces[(size_t)a].side);spectrumFifo.finishedWrite(1);}}}
bool PhasePocketAudioProcessor::popSpectrum(SpectrumTrace& v){int a,s,b,c;spectrumFifo.prepareToRead(1,a,s,b,c);if(!s)return false;v=spectrumTraces[(size_t)a];spectrumFifo.finishedRead(1);return true;}
bool PhasePocketAudioProcessor::popTrace(PocketTrace& v){int a,s,b,s2;fifo.prepareToRead(1,a,s,b,s2);if(!s)return false;v=traces[(size_t)a];fifo.finishedRead(1);return true;}
void PhasePocketAudioProcessor::getStateInformation(juce::MemoryBlock& d){auto state=parameters.copyState();state.setProperty("uiWidth",editorWidth.load(),nullptr);if(auto x=state.createXml())copyXmlToBinary(*x,d);}
void PhasePocketAudioProcessor::setStateInformation(const void* d,int n){if(auto x=getXmlFromBinary(d,n))if(x->hasTagName(parameters.state.getType())){auto state=juce::ValueTree::fromXml(*x);editorWidth.store((int)state.getProperty("uiWidth",0));parameters.replaceState(state);requestedMode.store(mode->load()>.5f?1:0);triggerAsyncUpdate();}}
juce::AudioProcessorEditor* PhasePocketAudioProcessor::createEditor(){return new PhasePocketAudioProcessorEditor(*this);}juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new PhasePocketAudioProcessor();}
