#include "PluginEditor.h"
#include <cstdlib>
namespace {
juce::Font font(float size,bool bold=false){
#if JUCE_LINUX
 return juce::Font(juce::FontOptions("Liberation Sans",size,bold?juce::Font::bold:juce::Font::plain));
#else
 return juce::Font(juce::FontOptions("Arial",size,bold?juce::Font::bold:juce::Font::plain));
#endif
}
void text(juce::Graphics& g,const juce::String& s,juce::Rectangle<float> r,float size,juce::Colour c,int align=juce::Justification::centredLeft){g.setColour(c);g.setFont(font(size));g.drawText(s,r,align);}
void line(juce::Graphics& g,float x1,float y1,float x2,float y2,juce::Colour c,float w=1){g.setColour(c);g.drawLine(x1,y1,x2,y2,w);}
bool parseNumber(juce::String s,float& value,bool hz=false){s=s.trim().toLowerCase().replace(",",".");double factor=hz&&s.contains("k")?1000:1;s=s.replace("khz","").replace("hz","").replace("ms","").replace("%","").trim();auto raw=s.toStdString();char* end=nullptr;double v=std::strtod(raw.c_str(),&end);if(end==raw.c_str()||*end!=0||!std::isfinite(v)||std::abs(v)>1e9)return false;value=(float)(v*factor);return true;}
void focus(juce::Graphics& g,juce::Component& c,ThemeTokens& t,float radius=10){if(c.hasKeyboardFocus(false)){g.setColour(t[ThemeTokens::focusRing]);g.drawRoundedRectangle(c.getLocalBounds().toFloat().reduced(2),radius,2);}}
}
ThemeTokens::ThemeTokens(bool d):dark(d){
 const juce::uint32 light[]={0xffF6F7F8,0xff1B2127,0xffF8F9FA,0xff20262D,0xff58636F,0xffE8EDF3,0xffACB7C2,0xff4D8FBE,0xffD8DEE5,0xffD8DDE2,0xff39424B,0xffC5DDEE,0xffEDF1F5,0xff8796A5,0xff97C4E3,0xffFFFFFF,0xff7E8C99,0xffE2E6EA,0xffFFFFFF,0xffE9EDF0,0xffE9EDF1,0xffDDE4EA,0xff171B20,0xff245F90};
 const juce::uint32 darks[]={0xff191D23,0xff101419,0xff242A32,0xffF1F4F8,0xffABB5C0,0xffE8EDF3,0xffACB7C2,0xff80B9E4,0xff3D4652,0xff343C46,0xff2A333D,0xffC5DDEE,0xffEDF1F5,0xff8796A5,0xff97C4E3,0xffD6E0E9,0xff91A3B5,0xff272F38,0xff414D5C,0xff303A46,0xffDDE4EA,0xffF0F3F6,0xff171B20,0xffA1D0F2};for(size_t i=0;i<c.size();++i)c[i]=juce::Colour(d?darks[i]:light[i]);}
ThemeStore::ThemeStore(){juce::PropertiesFile::Options o;o.applicationName="PhasePocket";o.filenameSuffix="settings";o.folderName="RainlineMusic";o.osxLibrarySubFolder="Application Support";file=std::make_unique<juce::PropertiesFile>(o);dark=file->getValue("phasePocket.ui.theme","light")=="dark";width=juce::jlimit(900,1800,file->getIntValue("phasePocket.ui.width",900));}
void ThemeStore::set(bool d){if(dark==d)return;dark=d;file->setValue("phasePocket.ui.theme",dark?"dark":"light");file->saveIfNeeded();sendChangeMessage();}
void ThemeStore::setWidth(int w){width=juce::jlimit(900,1800,w);file->setValue("phasePocket.ui.width",width);file->saveIfNeeded();}
void PhasePocketAudioProcessorEditor::MidSideSlider::paint(juce::Graphics& g){text(g,"M",{0,4,24,26},18,theme[ThemeTokens::textPrimary],juce::Justification::centred);text(g,"S",{172,4,24,26},18,theme[ThemeTokens::textPrimary],juce::Justification::centred);line(g,30,17,166,17,theme[ThemeTokens::inactiveTrack],3);for(float x:{30.f,98.f,166.f})line(g,x,10,x,24,theme[ThemeTokens::textSecondary]);float x=30+((float)getValue()+1)*68;line(g,98,17,x,17,theme[ThemeTokens::accent],3);g.setColour(theme[ThemeTokens::thumbFill]);g.fillEllipse(x-5,12,10,10);g.setColour(theme[ThemeTokens::thumbBorder]);g.drawEllipse(x-5,12,10,10,1);focus(g,*this,theme,6);}
Dial::Dial(juce::AudioProcessorValueTreeState& state,const juce::String& id,const juce::String& name,const juce::String& sub,const juce::String& units,ThemeTokens& t):theme(t),param(*state.getParameter(id)),attachment(param,[this](float v){setValue(v,juce::dontSendNotification);repaint();}),title(name),subtitle(sub),unit(units){setName(name);setSliderStyle(juce::Slider::RotaryVerticalDrag);setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);setRange(param.getNormalisableRange().start,param.getNormalisableRange().end,param.getNormalisableRange().interval);setWantsKeyboardFocus(true);setTextValueSuffix(" "+units);onValueChange=[this]{attachment.setValueAsCompleteGesture((float)getValue());};addChildComponent(entry);entry.onReturnKey=[this]{commit();};entry.onEscapeKey=[this]{entry.setVisible(false);grabKeyboardFocus();};entry.onFocusLost=[this]{entry.setVisible(false);};attachment.sendInitialUpdate();}
Dial::~Dial(){end();}
void Dial::paint(juce::Graphics& g){float cx=121,cy=121,r=112,p=param.convertTo0to1((float)getValue()),a=juce::MathConstants<float>::pi*(.75f+1.5f*p);juce::Path full,arc;full.addCentredArc(cx,cy,r,r,0,juce::MathConstants<float>::pi*1.25f,juce::MathConstants<float>::pi*2.75f,true);g.setColour(theme[ThemeTokens::inactiveTrack]);g.strokePath(full,juce::PathStrokeType(7,juce::PathStrokeType::curved,juce::PathStrokeType::rounded));if(p>0){arc.addCentredArc(cx,cy,r,r,0,juce::MathConstants<float>::pi*1.25f,juce::MathConstants<float>::pi*(1.25f+1.5f*p),true);g.setColour(theme[ThemeTokens::accent]);g.strokePath(arc,juce::PathStrokeType(7,juce::PathStrokeType::curved,juce::PathStrokeType::rounded));}g.setColour(theme[ThemeTokens::controlSurface]);g.fillEllipse(cx-100,cy-100,200,200);auto thumb=juce::Rectangle<float>(20,20).withCentre({cx+r*std::cos(a),cy+r*std::sin(a)});g.setColour(theme[ThemeTokens::thumbFill]);g.fillEllipse(thumb);g.setColour(theme[ThemeTokens::thumbBorder]);g.drawEllipse(thumb,1);text(g,title,{cx-94,cy-70,188,28},22,theme[ThemeTokens::textPrimary],juce::Justification::centred);text(g,subtitle,{cx-94,cy-39,188,24},18,theme[ThemeTokens::textSecondary],juce::Justification::centred);auto number=juce::String(getValue(),1);float width=0;for(auto c:number)width+=c=='.'?14.f:31.f;float x=cx-width*.5f;for(auto c:number){float w=c=='.'?14.f:31.f;text(g,juce::String::charToString(c),{x,cy-10,w,66},56,theme[ThemeTokens::textPrimary],juce::Justification::centred);x+=w;}text(g,unit,{cx-50,cy+58,100,24},18,theme[ThemeTokens::textSecondary],juce::Justification::centred);focus(g,*this,theme,18);}
void Dial::mouseDown(const juce::MouseEvent&){grabKeyboardFocus();startP=param.getValue();}
void Dial::mouseDrag(const juce::MouseEvent& e){float p=juce::jlimit(0.f,1.f,startP-e.getDistanceFromDragStartY()/(e.mods.isShiftDown()?2400.f:240.f)),v=param.convertFrom0to1(p);if(v==(float)getValue())return;if(!gesture){attachment.beginGesture();gesture=true;}attachment.setValueAsPartOfGesture(v);setValue(v,juce::dontSendNotification);repaint();}
void Dial::end(){if(gesture){attachment.endGesture();gesture=false;}}
void Dial::mouseUp(const juce::MouseEvent&){end();}void Dial::focusLost(FocusChangeType){end();repaint();}
void Dial::complete(float v){end();v=param.getNormalisableRange().snapToLegalValue(v);attachment.setValueAsCompleteGesture(v);setValue(v,juce::dontSendNotification);repaint();}
void Dial::mouseDoubleClick(const juce::MouseEvent& e){end();if(juce::Rectangle<float>(29,111,184,66).contains(e.position))edit();else complete(param.convertFrom0to1(param.getDefaultValue()));}
void Dial::edit(){entry.setBounds(29,111,184,66);entry.setFont(font(48));entry.setColour(juce::TextEditor::backgroundColourId,theme[ThemeTokens::controlSurface]);entry.setColour(juce::TextEditor::textColourId,theme[ThemeTokens::textPrimary]);entry.setColour(juce::TextEditor::outlineColourId,theme[ThemeTokens::focusRing]);entry.setText(juce::String(getValue(),1),false);entry.setVisible(true);entry.grabKeyboardFocus();entry.selectAll();}
void Dial::commit(){float v;if(!parseNumber(entry.getText(),v)){entry.setTooltip("Enter a finite number");entry.setColour(juce::TextEditor::outlineColourId,juce::Colours::red);return;}complete(v);entry.setVisible(false);grabKeyboardFocus();}
void Dial::mouseWheelMove(const juce::MouseEvent&,const juce::MouseWheelDetails& d){if(!hasKeyboardFocus(false)||d.deltaY==0)return;float delta=(d.deltaY>0?1.f:-1.f)*(juce::ModifierKeys::getCurrentModifiers().isShiftDown()?.001f:.01f);complete(param.convertFrom0to1(juce::jlimit(0.f,1.f,param.getValue()+delta)));}
bool Dial::keyPressed(const juce::KeyPress& k){int code=k.getKeyCode();if(code==juce::KeyPress::escapeKey){end();return true;}float step=param.getNormalisableRange().interval;if(step<=0)step=(float)(getMaximum()-getMinimum())*(k.getModifiers().isShiftDown()?.0005f:.005f);if(code==juce::KeyPress::homeKey)complete((float)getMinimum());else if(code==juce::KeyPress::endKey)complete((float)getMaximum());else if(code==juce::KeyPress::upKey||code==juce::KeyPress::rightKey)complete((float)getValue()+step);else if(code==juce::KeyPress::downKey||code==juce::KeyPress::leftKey)complete((float)getValue()-step);else if(code==juce::KeyPress::returnKey)edit();else return false;return true;}
RangeControl::RangeControl(juce::AudioProcessorValueTreeState& p,ThemeTokens& t):theme(t),lowParam(*p.getParameter("scLow")),highParam(*p.getParameter("scHigh")),lowAttach(lowParam,[this](float v){low=v;resized();repaint();}),highAttach(highParam,[this](float v){high=v;resized();repaint();}){addAndMakeVisible(lowHandle);addAndMakeVisible(highHandle);addAndMakeVisible(resetButton);resetButton.onClick=[this]{reset();};lowHandle.setExplicitFocusOrder(1);highHandle.setExplicitFocusOrder(2);resetButton.setExplicitFocusOrder(3);addChildComponent(entry);entry.onReturnKey=[this]{commit();};entry.onEscapeKey=[this]{entry.setVisible(false);};entry.onFocusLost=[this]{entry.setVisible(false);};setTooltip("Filter the sidechain only. Double-click a frequency to enter Hz or kHz.");lowAttach.sendInitialUpdate();highAttach.sendInitialUpdate();}
RangeControl::~RangeControl(){finish();}
float RangeControl::x(float v) const{return 26+std::log(juce::jlimit(20.f,20000.f,v)/20.f)/std::log(1000.f)*1072;}
void RangeControl::resized(){lowHandle.setBounds((int)x(low)-16,34,32,40);highHandle.setBounds((int)x(high)-16,34,32,40);resetButton.setBounds(1038,0,90,36);}
void RangeControl::paint(juce::Graphics& g){text(g,"Sidechain filter",{14,4,180,28},22,theme[ThemeTokens::textPrimary]);auto hz=[](float v){return v>=1000?juce::String(v/1000,1)+" kHz":juce::String((int)v)+" Hz";};text(g,hz(low),{196,4,90,28},22,theme[ThemeTokens::textPrimary]);line(g,288,8,288,30,theme[ThemeTokens::separator]);text(g,hz(high),{304,4,160,28},22,theme[ThemeTokens::textPrimary]);line(g,26,50,1098,50,theme[ThemeTokens::inactiveTrack],5);line(g,x(low),50,x(high),50,theme[ThemeTokens::accent],5);for(float f:{20.f,100.f,1000.f,10000.f,20000.f}){float px=x(f);line(g,px,64,px,69,theme[ThemeTokens::separator]);juce::String label=f>=1000?juce::String((int)(f/1000))+"k":juce::String((int)f);text(g,label,{px-24,71,48,22},18,theme[ThemeTokens::textSecondary],juce::Justification::centred);}}
void RangeControl::Handle::paint(juce::Graphics& g){auto r=juce::Rectangle<float>(6,6,20,20);g.setColour(owner.theme[ThemeTokens::thumbFill]);g.fillEllipse(r);g.setColour(owner.theme[ThemeTokens::thumbBorder]);g.drawEllipse(r,1);focus(g,*this,owner.theme,8);}
void RangeControl::Handle::mouseDown(const juce::MouseEvent&){grabKeyboardFocus();owner.finish();owner.active=owner.lastActive=index;}
void RangeControl::Handle::mouseDrag(const juce::MouseEvent& e){owner.drag(e.getEventRelativeTo(&owner).position.x);}void RangeControl::Handle::mouseUp(const juce::MouseEvent&){owner.finish();}
bool RangeControl::Handle::keyPressed(const juce::KeyPress& k){float current=index?owner.high:owner.low;int code=k.getKeyCode();if(code==juce::KeyPress::escapeKey){owner.finish();return true;}if(code==juce::KeyPress::returnKey){owner.edit(index);return true;}if(code==juce::KeyPress::homeKey)current=20;else if(code==juce::KeyPress::endKey)current=20000;else if(code==juce::KeyPress::upKey||code==juce::KeyPress::rightKey)current*=k.getModifiers().isShiftDown()?1.001f:1.01f;else if(code==juce::KeyPress::downKey||code==juce::KeyPress::leftKey)current/=k.getModifiers().isShiftDown()?1.001f:1.01f;else return false;owner.set(index,current);return true;}
void RangeControl::finish(){if(gesture){(active==0?lowAttach:highAttach).endGesture();gesture=false;}active=-1;}
void RangeControl::set(int which,float v,bool dragging){v=which?juce::jlimit(low,20000.f,v):juce::jlimit(20.f,high,v);auto& a=which?highAttach:lowAttach;auto& p=which?highParam:lowParam;v=p.getNormalisableRange().snapToLegalValue(v);if(v==(which?high:low))return;if(dragging){if(!gesture){a.beginGesture();gesture=true;}a.setValueAsPartOfGesture(v);}else a.setValueAsCompleteGesture(v);if(which)high=v;else low=v;resized();repaint();}
void RangeControl::drag(float px){if(active<0)return;set(active,20*std::pow(1000.f,juce::jlimit(0.f,1.f,(px-26)/1072)),true);}
void RangeControl::mouseDown(const juce::MouseEvent& e){if(e.position.y<32)return;finish();float a=std::abs(e.position.x-x(low)),b=std::abs(e.position.x-x(high));active=a==b?lastActive:a<b?0:1;lastActive=active;drag(e.position.x);}
void RangeControl::mouseDrag(const juce::MouseEvent& e){drag(e.position.x);}void RangeControl::mouseUp(const juce::MouseEvent&){finish();}
void RangeControl::reset(){finish();lowAttach.setValueAsCompleteGesture(lowParam.convertFrom0to1(lowParam.getDefaultValue()));highAttach.setValueAsCompleteGesture(highParam.convertFrom0to1(highParam.getDefaultValue()));}
void RangeControl::mouseDoubleClick(const juce::MouseEvent& e){if(e.position.y<34&&e.position.x>=194&&e.position.x<470)edit(e.position.x<290?0:1);}
void RangeControl::edit(int i){finish();editing=i;entry.setBounds(i?304:196,0,i?160:90,36);entry.setFont(font(22));entry.setColour(juce::TextEditor::backgroundColourId,theme[ThemeTokens::controlSurface]);entry.setColour(juce::TextEditor::textColourId,theme[ThemeTokens::textPrimary]);entry.setText(juce::String(i?high:low),false);entry.setVisible(true);entry.grabKeyboardFocus();entry.selectAll();}
void RangeControl::commit(){float v;if(!parseNumber(entry.getText(),v,true)){entry.setColour(juce::TextEditor::outlineColourId,juce::Colours::red);return;}set(editing,v);entry.setVisible(false);}
void PhasePocketAudioProcessorEditor::FlatLook::drawButtonBackground(juce::Graphics& g,juce::Button& b,const juce::Colour&,bool hover,bool down){if(b.getButtonText()=="Reset"){focus(g,b,theme);return;}g.setColour(theme[b.getToggleState()?ThemeTokens::segmentSelected:hover||down?ThemeTokens::hoverSurface:ThemeTokens::segmentBg]);g.fillRoundedRectangle(b.getLocalBounds().toFloat().reduced(1),8);focus(g,b,theme);}
juce::Font PhasePocketAudioProcessorEditor::FlatLook::getTextButtonFont(juce::TextButton&,int){return font(18);}
juce::Slider::SliderLayout PhasePocketAudioProcessorEditor::FlatLook::getSliderLayout(juce::Slider& s){auto layout=juce::LookAndFeel_V4::getSliderLayout(s);if(s.getName()=="Mid Side processing balance")layout.sliderBounds=juce::Rectangle<int>(30,0,136,s.getHeight());return layout;}
void PhasePocketAudioProcessorEditor::IconButton::paintButton(juce::Graphics& g,bool hover,bool down){using T=ThemeTokens;auto r=getLocalBounds().toFloat().reduced(1);g.setColour(theme[hover?T::iconButtonHover:T::iconButtonSurface]);g.fillRoundedRectangle(r,10);g.setColour(theme[T::iconInk].withAlpha(isPower&&getToggleState()?.55f:1.f));auto centre=r.getCentre();juce::Path p;if(isPower){p.addCentredArc(centre.x,centre.y+1,8,8,0,.65f,juce::MathConstants<float>::twoPi-.65f,true);p.startNewSubPath(centre.x,centre.y-10);p.lineTo(centre.x,centre.y-1);if(getToggleState()){p.startNewSubPath(centre.x-3,centre.y+14);p.lineTo(centre.x+3,centre.y+14);}}else if(theme.dark){p.addEllipse(centre.x-3.7f,centre.y-3.7f,7.4f,7.4f);for(int i=0;i<8;++i){float a=i*juce::MathConstants<float>::pi/4;p.startNewSubPath(centre.x+7*std::cos(a),centre.y+7*std::sin(a));p.lineTo(centre.x+9.5f*std::cos(a),centre.y+9.5f*std::sin(a));}}else{p.startNewSubPath(centre.x+8,centre.y+3);p.cubicTo(centre.x-4,centre.y+8,centre.x-10,centre.y-4,centre.x-2,centre.y-9);p.cubicTo(centre.x-16,centre.y-8,centre.x-9,centre.y+17,centre.x+8,centre.y+3);p.closeSubPath();}g.strokePath(p,juce::PathStrokeType(1.8f,juce::PathStrokeType::curved,juce::PathStrokeType::rounded));if(down){g.setColour(theme[T::iconInk].withAlpha(.18f));g.drawRoundedRectangle(r,10,1);}focus(g,*this,theme);}
PhasePocketAudioProcessorEditor::PhasePocketAudioProcessorEditor(PhasePocketAudioProcessor& p):AudioProcessorEditor(&p),processor(p),theme(themes->dark),influence(p.parameters,"amount","Influence","Depth","%",theme),smoothing(p.parameters,"release","Smoothing","Release / recovery","ms",theme),range(p.parameters,theme),bypassAttach(p.parameters,"bypass",bypassButton),modeAttach(*p.parameters.getParameter("mode"),[this](float v){amplitude.setToggleState(v>.5f,juce::dontSendNotification);spectrum.setToggleState(v<.5f,juce::dontSendNotification);repaint();}){
 look.setDefaultSansSerifTypefaceName(juce::Font::getDefaultSansSerifFontName());setLookAndFeel(&look);addAndMakeVisible(canvas);for(auto* c:std::initializer_list<juce::Component*>{&amplitude,&spectrum,&themeButton,&bypassButton,&influence,&smoothing,&range,&midSide})canvas.addAndMakeVisible(c);msAttach=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.parameters,"msBalance",midSide);midSide.setTooltip("Left: Mid only. Centre: Mid and Side. Right: Side only. Double-click to centre.");
 amplitude.peer=&spectrum;spectrum.peer=&amplitude;amplitude.onClick=[this]{modeAttach.setValueAsCompleteGesture(1);processor.syncModeLatency();};spectrum.onClick=[this]{modeAttach.setValueAsCompleteGesture(0);processor.syncModeLatency();};themeButton.onClick=[this]{themes->set(!themes->dark);applyTheme();};bypassButton.setClickingTogglesState(true);themeButton.setWantsKeyboardFocus(true);bypassButton.setWantsKeyboardFocus(true);amplitude.setTooltip("Amplitude: waveform-following full-band ducking.");spectrum.setTooltip("Spectrum: broad, phase-independent spectral ducking. Smoothing controls recovery.");influence.setTooltip("0-100% normal depth. 125% = 2.83x, 150% = 8x depth. Double-click the number to edit.");smoothing.setTooltip("Recovery time in milliseconds. Applies to both modes.");int order=1;for(auto* c:std::initializer_list<juce::Component*>{&amplitude,&spectrum,&themeButton,&bypassButton,&influence,&smoothing,&range})c->setExplicitFocusOrder(order++);
 setResizable(true,true);setResizeLimits(900,672,1800,1344);getConstrainer()->setFixedAspectRatio(75./56.);int initial=processor.editorWidth.load();if(initial<900||initial>1800)initial=themes->width;setSize(initial,juce::roundToInt(initial*56./75.));sizeReady=true;processor.editorWidth.store(initial);PocketTrace discard;while(processor.popTrace(discard)){}processor.editorOpen.store(true);themes->addChangeListener(this);applyTheme();modeAttach.sendInitialUpdate();startTimerHz(30);
}
PhasePocketAudioProcessorEditor::~PhasePocketAudioProcessorEditor(){themes->setWidth(getWidth());stopTimer();processor.editorOpen.store(false);themes->removeChangeListener(this);setLookAndFeel(nullptr);}
void PhasePocketAudioProcessorEditor::applyTheme(){theme=ThemeTokens(themes->dark);if(bypassLook)for(auto& c:theme.c)c=c.withSaturation(0.f);look.setColour(juce::TextButton::textColourOffId,theme[ThemeTokens::textSecondary]);look.setColour(juce::TextButton::textColourOnId,theme[ThemeTokens::textPrimary]);themeButton.setTooltip(theme.dark?"Switch to light theme":"Switch to dark theme");repaint();canvas.repaint();}
void PhasePocketAudioProcessorEditor::changeListenerCallback(juce::ChangeBroadcaster*){applyTheme();}void PhasePocketAudioProcessorEditor::setThemeForPreview(bool d){themes->set(d);applyTheme();}
void PhasePocketAudioProcessorEditor::resized(){float s=juce::jmin(getWidth()/1200.f,getHeight()/896.f);canvas.setBounds(0,0,1200,896);canvas.setTransform(juce::AffineTransform::scale(s));amplitude.setBounds(869,35,115,36);spectrum.setBounds(984,35,115,36);themeButton.setBounds(1108,33,36,40);bypassButton.setBounds(1150,33,36,40);influence.setBounds(924,137,242,242);smoothing.setBounds(924,441,242,242);range.setBounds(38,733,1128,96);midSide.setBounds(38,847,196,34);if(sizeReady){processor.editorWidth.store(getWidth());resizeStamp=juce::Time::getMillisecondCounterHiRes();}}
void PhasePocketAudioProcessorEditor::timerCallback(){if(resizeStamp>0&&juce::Time::getMillisecondCounterHiRes()-resizeStamp>500){themes->setWidth(getWidth());resizeStamp=0;}if(isShowing())refreshTrace();}
void PhasePocketAudioProcessorEditor::paintOverChildren(juce::Graphics& g){if(bypassLook){g.setColour(juce::Colours::grey.withAlpha(.28f));g.fillAll();}}
void PhasePocketAudioProcessorEditor::refreshTrace(){PocketTrace t;while(processor.popTrace(t)){if(!std::isfinite(t.time))continue;history[(size_t)cursor]=t;cursor=(cursor+1)%4096;filled=juce::jmin(filled+1,4096);}SpectrumTrace curve;while(processor.popSpectrum(curve))spectrumCurve=curve;spectrumMode=processor.parameters.getRawParameterValue("mode")->load()<.5f;bool dim=processor.parameters.getRawParameterValue("bypass")->load()>.5f||processor.displayBypass.load();if(dim!=bypassLook){bypassLook=dim;applyTheme();}bypassButton.setTooltip(dim?"Enable processing":"Bypass processing");repaint();}
void PhasePocketAudioProcessorEditor::paint(juce::Graphics& g){using T=ThemeTokens;g.fillAll(theme[T::windowBg]);g.addTransform(juce::AffineTransform::scale(juce::jmin(getWidth()/1200.f,getHeight()/896.f)));text(g,"Phase Pocket",{38,24,330,40},34,theme[T::textPrimary]);text(g,"RAINLINE",{40,67,220,20},18,theme[T::textSecondary]);g.setColour(theme[T::segmentBg]);g.fillRoundedRectangle(866,32,236,42,10);g.setColour(theme[T::analyzerBg]);g.fillRoundedRectangle(38,112,860,592,22);text(g,spectrumMode?"Spectral reduction":"Gain history",{64,136,500,32},24,theme[T::analyzerText]);text(g,"Oscilloscope",{64,430,500,32},24,theme[T::analyzerText]);auto plot=juce::Rectangle<float>(118,186,740,170);line(g,64,408,872,408,theme[T::analyzerGrid]);line(g,928,408,1162,408,theme[T::separator]);line(g,38,720,1166,720,theme[T::separator]);line(g,38,838,1166,838,theme[T::separator]);double now=filled?history[(size_t)((cursor+4095)%4096)].time:0;
 if(spectrumMode){auto y=[](float gain){return 186+170*(1-std::pow(juce::jlimit(0.f,1.f,gain),.25f));};for(float db:{0.f,-6.f,-12.f,-24.f,-48.f}){float yy=y(std::pow(10.f,db/20));line(g,118,yy,858,yy,theme[T::analyzerGrid]);text(g,db==0?juce::String("0 dB"):juce::String((int)db),{62,yy-12,52,24},18,theme[T::analyzerSecondary]);}text(g,juce::String::fromUTF8("-\xe2\x88\x9e"),{62,344,52,24},18,theme[T::analyzerSecondary]);for(float hz:{20.f,100.f,1000.f,10000.f,20000.f}){float x=118+740*std::log(hz/20)/std::log(1000.f);line(g,x,186,x,356,theme[T::analyzerGrid]);auto label=hz>=1000?juce::String((int)(hz/1000))+"k":juce::String((int)hz);text(g,label,{x-30,363,60,24},18,theme[T::analyzerSecondary],juce::Justification::centred);}text(g,"M",{780,137,28,24},18,theme[T::waveOut]);text(g,"S",{822,137,28,24},18,theme[T::waveIn]);juce::Graphics::ScopedSaveState saved(g);g.reduceClipRegion(plot.toNearestInt());for(int side=0;side<2;++side){const auto& values=side?spectrumCurve.side:spectrumCurve.mid;juce::Path path;for(int i=0;i<32;++i){float x=118+740*i/31.f,yy=y(std::isfinite(values[i])?values[i]:1.f);if(i==0)path.startNewSubPath(x,yy);else path.lineTo(x,yy);}g.setColour(theme[side?T::waveIn:T::waveOut]);g.strokePath(path,juce::PathStrokeType(1.7f));}}
 else{for(int i=0;i<=4;++i)line(g,118,186+i*42.5f,858,186+i*42.5f,theme[T::analyzerGrid]);for(int i=0;i<=5;++i)line(g,118+i*148,186,118+i*148,356,theme[T::analyzerGrid]);text(g,"100%",{62,174,52,24},18,theme[T::analyzerSecondary]);text(g,"0%",{62,341,52,24},18,theme[T::analyzerSecondary]);text(g,"-500 ms",{118,363,140,24},18,theme[T::analyzerSecondary]);text(g,"Now",{778,363,80,24},18,theme[T::analyzerSecondary],juce::Justification::centredRight);juce::Graphics::ScopedSaveState saved(g);g.reduceClipRegion(plot.toNearestInt());juce::Path trace;bool started=false;float first=858;for(int i=0;i<filled;++i){auto& v=history[(size_t)((cursor-filled+i+4096)%4096)];double age=now-v.time;if(age<0||age>.5||!std::isfinite(v.gain))continue;float px=(float)(858-age*1480),py=356-juce::jlimit(0.f,1.f,v.gain)*170;if(!started){trace.startNewSubPath(px,py);first=px;started=true;}else trace.lineTo(px,py);}if(started){auto fill=trace;fill.lineTo(858,356);fill.lineTo(first,356);fill.closeSubPath();g.setGradientFill(juce::ColourGradient(theme[T::graphMain].withAlpha(.1f),0,186,theme[T::graphMain].withAlpha(0.f),0,356,false));g.fillPath(fill);g.setColour(theme[T::graphMain]);g.strokePath(trace,juce::PathStrokeType(1.7f));}}
 {juce::Graphics::ScopedSaveState saved(g);g.reduceClipRegion(64,482,808,160);line(g,64,562,872,562,theme[T::analyzerGrid]);for(int kind=0;kind<2;++kind){std::array<float,808>lo{},hi{};std::array<bool,808>seen{};for(int i=0;i<filled;++i){auto& v=history[(size_t)((cursor-filled+i+4096)%4096)];double age=now-v.time;if(age<0||age>1)continue;int px=juce::jlimit(0,807,(int)(807-age*807));float l=kind?v.keyLo:v.outLo,h=kind?v.keyHi:v.outHi;if(!std::isfinite(l)||!std::isfinite(h))continue;if(!seen[px]){lo[px]=l;hi[px]=h;seen[px]=true;}else{lo[px]=juce::jmin(lo[px],l);hi[px]=juce::jmax(hi[px],h);}}g.setColour(kind?theme[T::waveIn]:theme[T::waveOut].withAlpha(.55f));for(int i=0;i<808;++i)if(seen[i]){float top=562-juce::jlimit(-1.f,1.f,hi[i])*80,bottom=562-juce::jlimit(-1.f,1.f,lo[i])*80;g.drawLine(64.f+i,top,64.f+i,juce::jmax(top+.5f,bottom),kind?1.3f:1.f);}}}
 text(g,"-1 s",{64,658,100,24},18,theme[T::analyzerSecondary]);text(g,"Now",{792,658,80,24},18,theme[T::analyzerSecondary],juce::Justification::centredRight);
#ifdef JucePlugin_VersionString
 text(g,"v" JucePlugin_VersionString,{1086,851,80,26},18,theme[T::textSecondary],juce::Justification::centredRight);
#else
 text(g,"dev",{1086,851,80,26},18,theme[T::textSecondary],juce::Justification::centredRight);
#endif
}
